parameters:
    twig.extension.form.class: Nuxia\Bundle\NuxiaBundle\Twig\FormExtension

services:
    nuxia.form.handler.abstract:
        class: Nuxia\Component\Form\Handler\AbstractFormHandler
        abstract: true
        calls:
            - [ "setRequestStack", [ "@request_stack" ] ]
            - [ "setRouter", [ "@router" ] ]
