services:
    security.authentication.provider.dao:
        class: Nuxia\Component\Security\Authentication\AuthenticationProvider
        abstract: true
        arguments: ["","@security.user_checker","","@security.encoder_factory","%security.authentication.hide_user_not_found%"]
        calls:
            - [ "setDisablePassword", [ "%nuxia.security.disable_password%" ] ]

    nuxia.security.manager.default:
        class: Nuxia\Component\Security\BaseSecurityManager
        public: false
        calls:
            - [ "setAuthorizationChecker", [ "@security.authorization_checker" ] ]
            - [ "setTokenStorage", [ "@security.token_storage" ] ]

    nuxia.security.manager:
        alias: "nuxia.security.manager.default"
