services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        public: false
        tags:
            - { name: "twig.extension" }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        public: false
        tags:
            - { name: "twig.extension" }

    nuxia.twig.extension.case:
        class: Nuxia\Bundle\NuxiaBundle\Twig\CaseExtension
        public: false
        tags:
            -  { name: "twig.extension" }

    nuxia.twig.extension.object:
        class: Nuxia\Bundle\NuxiaBundle\Twig\ObjectExtension
        public: false
        tags:
            -  { name: "twig.extension" }

    nuxia.twig.extension.html:
        class: Nuxia\Bundle\NuxiaBundle\Twig\HtmlExtension
        public: false
        tags:
            -  { name: "twig.extension" }

    nuxia.twig.extension.form:
        class: Nuxia\Bundle\NuxiaBundle\Twig\FormExtension
        public: false
        tags:
            -  { name: "twig.extension" }
